# Generated by Django 4.1 on 2024-09-18 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=100, verbose_name='club_name')),
                ('club_phone', models.CharField(max_length=100, verbose_name='club_phone')),
                ('club_email', models.CharField(max_length=100, verbose_name='club_email')),
                ('club_address', models.CharField(max_length=300, verbose_name='club_address')),
                ('club_banner', models.FileField(upload_to='images/', verbose_name='club_banner')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='district',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100, verbose_name='district')),
            ],
        ),
        migrations.CreateModel(
            name='locations',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.district')),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('packid', models.AutoField(primary_key=True, serialize=False)),
                ('pack_name', models.CharField(max_length=100, verbose_name='pack_name')),
                ('pack_rate', models.IntegerField()),
                ('pack_type', models.CharField(max_length=100, verbose_name='pack_type')),
                ('pack_status', models.CharField(max_length=100, verbose_name='pack_status')),
                ('pack_image', models.FileField(max_length=500, upload_to='package/', verbose_name='pack_image')),
            ],
        ),
        migrations.CreateModel(
            name='payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('pay_date', models.CharField(max_length=100, verbose_name='pay_status')),
            ],
        ),
        migrations.CreateModel(
            name='saleitem',
            fields=[
                ('sitem_id', models.AutoField(primary_key=True, serialize=False)),
                ('sitem_name', models.CharField(max_length=100, verbose_name='sitem_name')),
                ('sitem_photo', models.FileField(upload_to='item/', verbose_name='sitem_image')),
                ('sitem_description', models.CharField(max_length=500, verbose_name='sitem_description')),
                ('sitem_stock', models.IntegerField()),
                ('sitem_price', models.IntegerField()),
                ('sitem_status', models.CharField(max_length=100, verbose_name='sitem_status')),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=100, verbose_name='shop_name')),
                ('shop_phone', models.CharField(max_length=100, verbose_name='shop_phone')),
                ('shop_email', models.CharField(max_length=100, verbose_name='shop_email')),
                ('shop_address', models.CharField(max_length=300, verbose_name='shop_address')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.district')),
                ('locations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.locations')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='turf',
            fields=[
                ('turf_id', models.AutoField(primary_key=True, serialize=False)),
                ('turf_name', models.CharField(max_length=100, verbose_name='turf_name')),
                ('turf_phone', models.CharField(max_length=100, verbose_name='turf_phone')),
                ('turf_email', models.CharField(max_length=100, verbose_name='turf_email')),
                ('turf_address', models.CharField(max_length=300, verbose_name='turf_address')),
                ('turf_squarefeet', models.CharField(max_length=100, verbose_name='turf_squarefeet')),
                ('turf_ownername', models.CharField(max_length=100, verbose_name='turf_ownername')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.district')),
                ('locations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.locations')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, verbose_name='user_name')),
                ('user_phone', models.CharField(max_length=100, verbose_name='user_phone')),
                ('user_email', models.CharField(max_length=100, verbose_name='user_email')),
                ('user_contact', models.CharField(max_length=100, verbose_name='user_contact')),
                ('status', models.CharField(max_length=100, verbose_name='status:')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.district')),
                ('locations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.locations')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='turfcomplaint',
            fields=[
                ('tcomplaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('tsubject', models.CharField(max_length=200, verbose_name='tsubject')),
                ('tmsg', models.CharField(max_length=500, verbose_name='tmessage')),
                ('creply', models.CharField(max_length=500, verbose_name='treply')),
                ('tcomplaint_date', models.CharField(max_length=100, verbose_name='tdate')),
                ('turf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.turf')),
            ],
        ),
        migrations.CreateModel(
            name='tournament',
            fields=[
                ('tour_id', models.AutoField(primary_key=True, serialize=False)),
                ('tour_name', models.CharField(max_length=100, verbose_name='tour_name')),
                ('tour_details', models.CharField(max_length=500, verbose_name='tour_details')),
                ('tour_venue', models.CharField(max_length=100, verbose_name='tour_venue')),
                ('tour_time', models.CharField(max_length=100, verbose_name='tour_time')),
                ('tour_date', models.CharField(max_length=100, verbose_name='tour_date')),
                ('ticketcharge', models.CharField(max_length=100, verbose_name='ticketcharge')),
                ('no_tickets', models.CharField(max_length=100, verbose_name='no_tickets')),
                ('tour_status', models.CharField(max_length=100, verbose_name='status')),
                ('soldcount', models.CharField(max_length=100, verbose_name='tickets sold')),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.club')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.district')),
                ('locations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.locations')),
            ],
        ),
        migrations.CreateModel(
            name='ticketbooking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('bookdate', models.CharField(max_length=100, verbose_name='bookdate')),
                ('ticketcount', models.CharField(max_length=100, verbose_name='ticketcount')),
                ('ticket_status', models.CharField(max_length=100, verbose_name='ticket_status')),
                ('payamount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments2', to='tapp.payments')),
                ('paydate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments1', to='tapp.payments')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.tournament')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_quantity', models.CharField(max_length=100, verbose_name='quantity')),
                ('stock_itemprice', models.CharField(max_length=100, verbose_name='price')),
                ('stock_itembrand', models.CharField(max_length=100, verbose_name='brand')),
                ('stock_status', models.CharField(max_length=100, verbose_name='stock_status')),
                ('saleitem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.saleitem')),
            ],
        ),
        migrations.CreateModel(
            name='shopcomplaint',
            fields=[
                ('scomplaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('ssubject', models.CharField(max_length=200, verbose_name='ssubject')),
                ('smsg', models.CharField(max_length=500, verbose_name='smessage')),
                ('sreply', models.CharField(max_length=500, verbose_name='sreply')),
                ('scomplaint_date', models.CharField(max_length=100, verbose_name='sdate')),
                ('shop_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.shop')),
            ],
        ),
        migrations.AddField(
            model_name='saleitem',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.shop'),
        ),
        migrations.CreateModel(
            name='rentitems',
            fields=[
                ('rentid', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100, verbose_name='item_name')),
                ('item_image', models.FileField(max_length=500, upload_to='rentItems/', verbose_name='item_image')),
                ('item_rph', models.IntegerField()),
                ('item_status', models.CharField(max_length=100, verbose_name='item_status')),
                ('rent_turf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.turf')),
            ],
        ),
        migrations.CreateModel(
            name='rentbookings',
            fields=[
                ('rbookid', models.AutoField(primary_key=True, serialize=False)),
                ('rent_hours', models.IntegerField()),
                ('rbook_date', models.CharField(max_length=100, verbose_name='rbook_date')),
                ('book_status', models.CharField(max_length=100, verbose_name='book_status')),
                ('pay_status', models.CharField(max_length=100, verbose_name='pay_status')),
                ('rent_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.rentitems')),
                ('rent_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.user')),
                ('turf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.turf')),
            ],
        ),
        migrations.CreateModel(
            name='pbooking',
            fields=[
                ('pbookid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100, verbose_name='date')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.package')),
                ('turf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.turf')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='payments',
            name='rent_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.rentbookings'),
        ),
        migrations.AddField(
            model_name='package',
            name='pack_turf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.turf'),
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.CharField(max_length=100, verbose_name='order_status')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.shop')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='orderitem',
            fields=[
                ('order_itemid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=100, verbose_name='quantity')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.saleitem')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('msg', models.CharField(max_length=500, verbose_name='message')),
                ('reply', models.CharField(max_length=500, verbose_name='reply')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='clubcomplaint',
            fields=[
                ('ccomplaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('csubject', models.CharField(max_length=200, verbose_name='csubject')),
                ('cmsg', models.CharField(max_length=500, verbose_name='cmessage')),
                ('creply', models.CharField(max_length=500, verbose_name='creply')),
                ('ccomplaint_date', models.CharField(max_length=100, verbose_name='cdate')),
                ('club_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.club')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.district'),
        ),
        migrations.AddField(
            model_name='club',
            name='locations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.locations'),
        ),
        migrations.AddField(
            model_name='club',
            name='login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.login'),
        ),
    ]
