from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .import views

urlpatterns=[
    path('',views.index,name="index"),
    path('index',views.index,name="index"),
    # path('adlogin',views.adlogin,name="adlogin"),
    path('admin',views.admin,name="admin"),
    path('adminhome',views.adminhome,name="adminhome"),
    path("stafflogin",views.stafflogin,name="stafflogin"),
    path("userhome",views.userhome,name="userhome"),
    path("guest",views.guest,name="guest"),
    # path("shophome",views.shophome,name="shophome"),
    # path("clubhome",views.clubhome,name="clubhome"),
    
    

    # path('privacy',views.privacy,name="privacy"),
    path('add_district',views.add_district,name="add_district"),
    path('list_district',views.list_district,name="list_district"),
    path('logout',views.logout,name="logout"),
    path('add_location',views.add_location,name="add_location"),
    path('list_location',views.list_location,name="list_location"),
    path('edit_location',views.edit_location,name="edit_location"),
    path('delete_location',views.delete_location,name="delete_location"),
     path('delete_dis',views.delete_dis,name="delete_dis"),
    path("getLocation/",views.getLocation,name="getLocation"),

    path('userreg',views.userreg,name="userreg"),
    path('approve_user',views.approve_user,name="approve_user"),
    path('approved_user',views.approved_user,name="approved_user"),
    path('reject_user',views.reject_user,name="reject_user"),
    path('list_user',views.list_user,name="list_user"),
    path('delete_user',views.delete_user,name="delete_user"),

    path('userFeedback',views.userFeedback,name="userFeedback"),
    path("userAddFeedback",views.userAddFeedback,name="userAddFeedback"),
    path('user_feedback',views.user_feedback,name="user_feedback"),

    # path('shopreg',views.shopreg,name="shopreg"),
    path('shopProfile',views.shopProfile,name="shopProfile"),
    path('shopProfileUpdate',views.shopProfileUpdate,name="shopProfileUpdate"),
    # path('approve_shop',views.approve_shop,name="approve_shop"),
    # path('approved_shop',views.approved_shop,name="approved_shop"),
    path('reject_shop',views.reject_shop,name="reject_shop"),
    # path('list_shop',views.list_shop,name="list_shop"),
    # path('delete_shop',views.delete_shop,name="delete_shop"),
    # path('shopComplaints',views.shopComplaints,name="shopComplaints"),
    # path('shopAddComplaint',views.shopAddComplaint,name="shopAddComplaint"),
    # path("shop_feed",views.shop_feed,name="shop_feed"),
    # path("shopRegisterItem",views.shopRegisterItem,name="shopRegisterItem"),
    # path("shopRegisterItemProcess",views.shopRegisterItemProcess,name="shopRegisterItemProcess"),
    # path("shopItemList",views.shopItemList,name="shopItemList"),
    # path("shopItemUpdate",views.shopItemUpdate,name="shopItemUpdate"),
    # path("shopItemDelete",views.shopItemDelete,name="shopItemDelete"),
    # path("shopRegisterStock",views.shopRegisterStock,name="shopRegisterStock"),
    # path("shopRegisterStockProcess",views.shopRegisterStockProcess,name="shopRegisterStockProcess"),
    # path("shopStockList",views.shopStockList,name="shopStockList"),
    # path("shopStockUpdate",views.shopStockUpdate,name="shopStockUpdate"),
    # path("shopStockDelete",views.shopStockDelete,name="shopStockDelete"),

    # path("newOrderBookings",views.newOrderBookings,name="newOrderBookings"),
    # path("newOrderBookinApprove",views.newOrderBookinApprove,name="newOrderBookinApprove"),
    # path("shopItemPaidBookings",views.shopItemPaidBookings,name="shopItemPaidBookings"),

    # path('clubreg',views.clubreg,name="clubreg"),
    # path('clubProfile',views.clubProfile,name="clubProfile"),
    # path('clubProfileUpdate',views.clubProfileUpdate,name="clubProfileUpdate"),
    # path('approve_club',views.approve_club,name="approve_club"),
    # path('approved_club',views.approved_club,name="approved_club"),
    # path('reject_club',views.reject_club,name="reject_club"),
    # path('list_club',views.list_club,name="list_club"),
    # path('delete_club',views.delete_club,name="delete_club"),
    # path('clubComplaints',views.clubComplaints,name="clubComplaints"),
    # path('clubAddComplaint',views.clubAddComplaint,name="clubAddComplaint"),
    # path('club_feed',views.club_feed,name="club_feed"),
    # path('clubRegisterTour',views.clubRegisterTour,name="clubRegisterTour"),
    # path('tournament',views.tournament,name="tournament"),
    # path('clubTourList',views.clubTourList,name="clubTourList"),
    # path('clubTourUpdate',views.clubTourUpdate,name="clubTourUpdate"),
    # path('clubTourDelete',views.clubTourDelete,name="clubTourDelete"),
    # path('approve_tour',views.approve_tour,name="approve_tour"),
    # path('approved_tour',views.approved_tour,name="approved_tour"),
    # path('tour_approve',views.tour_approve,name="tour_approve"),
    # path('tour_approval',views.tour_approval,name="tour_approval"),
    # path('approved_tournament',views.approved_tournament,name="approved_tournament"),

    path('turfreg',views.turfreg,name="turfreg"),
    path('approve_turf',views.approve_turf,name="approve_turf"),
    path('approved_turf',views.approved_turf,name="approved_turf"),
    path('reject_turf',views.reject_turf,name="reject_turf"),
    path('list_turf',views.list_turf,name="list_turf"),
    path('delete_turf',views.delete_turf,name="delete_turf"),
    path('turf_feed',views.turf_feed,name="turf_feed"),


    path('usrPackageNewBookings',views.usrPackageNewBookings,name="usrPackageNewBookings"),
    path('usrPackageApprovedBookings',views.usrPackageApprovedBookings,name="usrPackageApprovedBookings"),
    path('usrPackageCancelledBookings',views.usrPackageCancelledBookings,name="usrPackageCancelledBookings"),




    
    path('turfhome',views.turfhome,name="turfhome"),
    path('turfPrivacy',views.turfPrivacy,name="turfPrivacy"),
    path('turfRegisterPackage',views.turfRegisterPackage,name="turfRegisterPackage"),
    path('turfRegisterPackageProcess',views.turfRegisterPackageProcess,name="turfRegisterPackageProcess"),
    path('turfPackageList',views.turfPackageList,name="turfPackageList"),
    path('turfPackageUpdate',views.turfPackageUpdate,name="turfPackageUpdate"),
    path('turfPackageDelete',views.turfPackageDelete,name="turfPackageDelete"),
    path('turfPackageNewBookings',views.turfPackageNewBookings,name="turfPackageNewBookings"),
    path('turfPackageBookingApprove',views.turfPackageBookingApprove,name="turfPackageBookingApprove"),
    path('turfPackageBookingReject',views.turfPackageBookingReject,name="turfPackageBookingReject"),
    path('turfPackageApprovedBookings',views.turfPackageApprovedBookings,name="turfPackageApprovedBookings"),
    path('turfPackageRescheduleRequests',views.turfPackageRescheduleRequests,name="turfPackageRescheduleRequests"),
    path('turfPackageRescheduleApprove',views.turfPackageRescheduleApprove,name="turfPackageRescheduleApprove"),
    path('turfPackageRescheduleReject',views.turfPackageRescheduleReject,name="turfPackageRescheduleReject"),
    path('turfPackageRescheduledBookings',views.turfPackageRescheduledBookings,name="turfPackageRescheduledBookings"),
    path('turfPackageCancelledBookings',views.turfPackageCancelledBookings,name="turfPackageCancelledBookings"),
    path('turfComplaints',views.turfComplaints,name="turfComplaints"),
    path('turfAddComplaint',views.turfAddComplaint,name="turfAddComplaint"),
    path('turfProfile',views.turfProfile,name="turfProfile"),
    path('turfProfileUpdate',views.turfProfileUpdate,name="turfProfileUpdate"),
    # path('turfAddItems',views.turfAddItems,name="turfAddItems"),
    # path('turfAddItemsProcess',views.turfAddItemsProcess,name="turfAddItemsProcess"),
    # path('turfRentItems',views.turfRentItems,name="turfRentItems"),
    # path('turfRentItemUpdate',views.turfRentItemUpdate,name="turfRentItemUpdate"),
    # path('turfRentItemDelete',views.turfRentItemDelete,name="turfRentItemDelete"),
    # path('turfRentItemNewBookings',views.turfRentItemNewBookings,name="turfRentItemNewBookings"),
    # path('turfRentItemBookingApprove',views.turfRentItemBookingApprove,name="turfRentItemBookingApprove"),
    # path('turfRentItemBookingReject',views.turfRentItemBookingReject,name="turfRentItemBookingReject"),
    # path('turfRentItemApprovedBookings',views.turfRentItemApprovedBookings,name="turfRentItemApprovedBookings"),
    # path('turfRentItemRejectedBookings',views.turfRentItemRejectedBookings,name="turfRentItemRejectedBookings"),
    # path('turfRentItemCancelledBookings',views.turfRentItemCancelledBookings,name="turfRentItemCancelledBookings"),
    # path('turfRentItemBookingRefund',views.turfRentItemBookingRefund,name="turfRentItemBookingRefund"),

    # path('clubRegisterTicket',views.clubRegisterTicket,name="clubRegisterTicket"),
    # path('ticket',views.ticket,name="ticket"),
    # path('clubTicketList',views.clubTicketList,name="clubTicketList"),


    path('usershome',views.usershome,name="usershome"),
    path('userPrivacy',views.userPrivacy,name="userPrivacy"),
    path('searchturf',views.searchturf,name='searchturf'),
    path('book',views.book,name="book"),
    path('listpack',views.listpack,name="listpack"),
    path('bookturf',views.bookturf,name="bookturf"),
    path('itemlist',views.itemlist,name="itemlist"),



    # path("clubPrivacy",views.clubPrivacy,name="clubPrivacy"),
    # path("shopPrivacy",views.shopPrivacy,name="shopPrivacy"),

    # path('app_login',views.app_login,name="app_login"),
    # path('app_register',views.app_register,name="app_register"),
    # path('app_getdistrict',views.app_getdistrict,name="app_getdistrict"),
    # path('app_getlocation',views.app_getlocation,name="app_getlocation"),
    # path('app_getUserProfile',views.app_getUserProfile,name="app_getUserProfile"),
    # path('app_changePassword',views.app_changePassword,name="app_changePassword"),
    # path('app_getTurfList',views.app_getTurfList,name="app_getTurfList"),
    # path('app_getTurfPackages',views.app_getTurfPackages,name="app_getTurfPackages"),
    # path('app_bookPackage',views.app_bookPackage,name="app_bookPackage"),
    # path('app_getPackageBookings',views.app_getPackageBookings,name="app_getPackageBookings"),
    # path('app_rescheduleBooking',views.app_rescheduleBooking,name="app_rescheduleBooking"),
    # path('app_cancelTurfBooking',views.app_cancelTurfBooking,name="app_cancelTurfBooking"),
    # path('app_getRentItems',views.app_getRentItems,name="app_getRentItems"),
    # path('app_bookRentItem',views.app_bookRentItem,name="app_bookRentItem"),
    # path('app_getRentItemBookings',views.app_getRentItemBookings,name="app_getRentItemBookings"),
    # path('app_cancelItemBooking',views.app_cancelItemBooking,name="app_cancelItemBooking"),
    # path('app_getTournament',views.app_getTournament,name="app_getTournament"),
    # path('app_bookTicket',views.app_bookTicket,name="app_bookTicket"),
    # path('app_getBookedTickets',views.app_getBookedTickets,name="app_getBookedTickets"),
    # path('app_getShopList',views.app_getShopList,name="app_getShopList"),
    # path('app_getShopProducts',views.app_getShopProducts,name="app_getShopProducts"),
    # path('app_bookProduct',views.app_bookProduct,name="app_bookProduct"),
    # path('app_getCartItems',views.app_getCartItems,name="app_getCartItems"),
    # path('app_PlaceOrder',views.app_PlaceOrder,name="app_PlaceOrder"),
    # path('app_getOrderHistory',views.app_getOrderHistory,name="app_getOrderHistory"),


    

    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)