# Generated by Django 5.2.11 on 2026-05-26 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100, unique=True, verbose_name='district')),
            ],
            options={
                'verbose_name': 'district',
                'verbose_name_plural': 'districts',
                'ordering': ['district'],
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('logid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('turf', 'Turf owner')], max_length=10, verbose_name='role')),
            ],
            options={
                'verbose_name': 'login',
                'verbose_name_plural': 'logins',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.district')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': ['district__district', 'location'],
            },
        ),
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('turf_id', models.AutoField(primary_key=True, serialize=False)),
                ('turf_name', models.CharField(max_length=100, verbose_name='turf_name')),
                ('turf_phone', models.CharField(max_length=20, verbose_name='turf_phone')),
                ('turf_email', models.EmailField(max_length=100, verbose_name='turf_email')),
                ('turf_address', models.CharField(max_length=300, verbose_name='turf_address')),
                ('turf_squarefeet', models.CharField(blank=True, max_length=100, verbose_name='turf_squarefeet')),
                ('turf_ownername', models.CharField(blank=True, max_length=100, verbose_name='turf_ownername')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='waiting', max_length=100, verbose_name='status')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.district')),
                ('locations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.locations')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.login')),
            ],
            options={
                'verbose_name': 'turf',
                'verbose_name_plural': 'turfs',
                'ordering': ['turf_name'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('packid', models.AutoField(primary_key=True, serialize=False)),
                ('pack_name', models.CharField(max_length=100, verbose_name='pack_name')),
                ('pack_rate', models.IntegerField()),
                ('pack_type', models.CharField(max_length=100, verbose_name='pack_type')),
                ('pack_image', models.FileField(blank=True, max_length=500, upload_to='packages/', verbose_name='pack_image')),
                ('pack_status', models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='approved', max_length=100, verbose_name='pack_status')),
                ('pack_turf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.turf')),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
                'ordering': ['pack_turf__turf_name', 'pack_name'],
            },
        ),
        migrations.CreateModel(
            name='TurfComplaint',
            fields=[
                ('tcomplaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('tsubject', models.CharField(max_length=100, verbose_name='tsubject')),
                ('tmsg', models.CharField(max_length=300, verbose_name='tmsg')),
                ('tcomplaint_date', models.DateField(verbose_name='tcomplaint_date')),
                ('creply', models.CharField(default='pending', max_length=300, verbose_name='creply')),
                ('turf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.turf')),
            ],
            options={
                'verbose_name': 'turf complaint',
                'verbose_name_plural': 'turf complaints',
                'ordering': ['-tcomplaint_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, verbose_name='user_name')),
                ('user_phone', models.CharField(max_length=20, verbose_name='user_phone')),
                ('user_email', models.EmailField(max_length=100, verbose_name='user_email')),
                ('user_contact', models.CharField(blank=True, max_length=100, verbose_name='user_contact')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='approved', max_length=100, verbose_name='status')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.district')),
                ('locations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.locations')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.login')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['user_name'],
            },
        ),
        migrations.CreateModel(
            name='PBooking',
            fields=[
                ('pbookid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='date')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='waiting', max_length=100, verbose_name='status')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.package')),
                ('turf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.turf')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.user')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ['-date', '-pbookid'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('msg', models.CharField(max_length=300, verbose_name='msg')),
                ('reply', models.CharField(default='pending', max_length=300, verbose_name='reply')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.user')),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedback',
                'ordering': ['-feedback_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='locations',
            constraint=models.UniqueConstraint(fields=('district', 'location'), name='unique_location_per_district'),
        ),
        migrations.AddConstraint(
            model_name='pbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['waiting', 'approved'])), fields=('package', 'date'), name='unique_active_package_booking_per_date'),
        ),
    ]
