# Generated by Django 5.2.11 on 2026-02-14 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='district',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100, verbose_name='district')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('logid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('role', models.CharField(max_length=10, verbose_name='role')),
            ],
        ),
        migrations.CreateModel(
            name='rentbookings',
            fields=[
                ('rbookid', models.AutoField(primary_key=True, serialize=False)),
                ('rent_hours', models.IntegerField()),
                ('rbook_date', models.CharField(max_length=100, verbose_name='rbook_date')),
                ('book_status', models.CharField(max_length=100, verbose_name='book_status')),
                ('pay_status', models.CharField(max_length=100, verbose_name='pay_status')),
            ],
        ),
        migrations.CreateModel(
            name='rentitems',
            fields=[
                ('rentid', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100, verbose_name='item_name')),
                ('item_image', models.FileField(max_length=500, upload_to='rentItems/', verbose_name='item_image')),
                ('item_rph', models.IntegerField()),
                ('item_status', models.CharField(max_length=100, verbose_name='item_status')),
            ],
        ),
        migrations.CreateModel(
            name='locations',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.district')),
            ],
        ),
        migrations.CreateModel(
            name='payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('pay_date', models.CharField(max_length=100, verbose_name='pay_status')),
                ('rent_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.rentbookings')),
            ],
        ),
        migrations.AddField(
            model_name='rentbookings',
            name='rent_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.rentitems'),
        ),
        migrations.CreateModel(
            name='turf',
            fields=[
                ('turf_id', models.AutoField(primary_key=True, serialize=False)),
                ('turf_name', models.CharField(max_length=100, verbose_name='turf_name')),
                ('turf_phone', models.CharField(max_length=100, verbose_name='turf_phone')),
                ('turf_email', models.CharField(max_length=100, verbose_name='turf_email')),
                ('turf_address', models.CharField(max_length=300, verbose_name='turf_address')),
                ('turf_squarefeet', models.CharField(max_length=100, verbose_name='turf_squarefeet')),
                ('turf_ownername', models.CharField(max_length=100, verbose_name='turf_ownername')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.district')),
                ('locations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.locations')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.login')),
            ],
        ),
        migrations.AddField(
            model_name='rentitems',
            name='rent_turf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.turf'),
        ),
        migrations.AddField(
            model_name='rentbookings',
            name='turf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.turf'),
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('packid', models.AutoField(primary_key=True, serialize=False)),
                ('pack_name', models.CharField(max_length=100, verbose_name='pack_name')),
                ('pack_rate', models.IntegerField()),
                ('pack_type', models.CharField(max_length=100, verbose_name='pack_type')),
                ('pack_image', models.FileField(max_length=500, upload_to='packages/', verbose_name='pack_image')),
                ('pack_status', models.CharField(max_length=100, verbose_name='pack_status')),
                ('pack_turf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.turf')),
            ],
        ),
        migrations.CreateModel(
            name='turfcomplaint',
            fields=[
                ('tcomplaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('tsubject', models.CharField(max_length=100, verbose_name='tsubject')),
                ('tmsg', models.CharField(max_length=300, verbose_name='tmsg')),
                ('tcomplaint_date', models.CharField(max_length=100, verbose_name='tcomplaint_date')),
                ('creply', models.CharField(default='pending', max_length=300, verbose_name='creply')),
                ('turf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.turf')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, verbose_name='user_name')),
                ('user_phone', models.CharField(max_length=100, verbose_name='user_phone')),
                ('user_email', models.CharField(max_length=100, verbose_name='user_email')),
                ('user_contact', models.CharField(max_length=100, verbose_name='user_contact')),
                ('status', models.CharField(max_length=100, verbose_name='status:')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.district')),
                ('locations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.locations')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.login')),
            ],
        ),
        migrations.AddField(
            model_name='rentbookings',
            name='rent_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.user'),
        ),
        migrations.CreateModel(
            name='pbooking',
            fields=[
                ('pbookid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100, verbose_name='date')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.package')),
                ('turf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.turf')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('msg', models.CharField(max_length=300, verbose_name='msg')),
                ('reply', models.CharField(default='pending', max_length=300, verbose_name='reply')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tapp.user')),
            ],
        ),
    ]
